import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{seedItems,recommendations}from'./data';
import{supabase,hasSupabase}from'./lib/supabase';
import'./styles.css';

const LS_ITEMS='morgana-hub-items-v2';
const LS_CHECK='morgana-hub-checklist-v2';
const LS_GIFTS='morgana-hub-gifts-v2';
const LS_EVENTS='morgana-hub-events-v2';
const DUE_DATE='2026-11-17';
const fmt=n=>new Intl.NumberFormat('pt-BR').format(Number(n)||0);
const priRank={Alta:0,Média:1,Condicional:2,Baixa:3};
const slug=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const missingRecs=recommendations.filter(r=>r.status==='FALTA').sort((a,b)=>(priRank[a.priority]??9)-(priRank[b.priority]??9));
const seedChecklist=missingRecs.map(r=>({id:`check-${slug(r.item)}`,name:r.item,category:r.category,quantity:Math.max(1,r.min-r.current),priority:r.priority,note:r.note,size:'',age:'',unit:r.category.includes('Roupas')?'peça':'unid.'}));
const seedGifts=missingRecs.filter(r=>r.priority!=='Condicional').map(r=>({id:`gift-${slug(r.item)}`,name:r.item,category:r.category,quantity:Math.max(1,r.min-r.current),status:'available',buyer:'',note:r.note,purchased_at:null,received_at:null}));

function safeLoad(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function saveLocal(key,value){localStorage.setItem(key,JSON.stringify(value))}
function dateOnly(d){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d)}
function isoLocalDate(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${day}`}

function App(){
 const[tab,setTab]=useState('inicio');
 const[items,setItems]=useState(seedItems);
 const[checklist,setChecklist]=useState(seedChecklist);
 const[gifts,setGifts]=useState(seedGifts);
 const[events,setEvents]=useState([]);
 const[q,setQ]=useState('');const[cat,setCat]=useState('Todas');
 const[showItem,setShowItem]=useState(false);const[showEvent,setShowEvent]=useState(false);const[giftChoice,setGiftChoice]=useState(null);
 const[sync,setSync]=useState(hasSupabase?'conectando':'local');
 const[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));

 useEffect(()=>{(async()=>{
   const keyOf=x=>`${x.category}|${x.name}|${x.size||''}`;
   if(!hasSupabase){
     const savedItems=safeLoad(LS_ITEMS,seedItems);const existing=new Set(savedItems.map(keyOf));
     setItems([...seedItems.filter(x=>x.category==='Fraldas'&&!existing.has(keyOf(x))),...savedItems]);
     setChecklist(safeLoad(LS_CHECK,seedChecklist));setGifts(safeLoad(LS_GIFTS,seedGifts));setEvents(safeLoad(LS_EVENTS,[]));return;
   }
   setSync('conectando');
   const [ir,cr,gr,er]=await Promise.all([
     supabase.from('items').select('*').order('created_at'),
     supabase.from('checklist').select('*').order('created_at'),
     supabase.from('gifts').select('*').order('created_at'),
     supabase.from('calendar_events').select('*').order('event_date').order('event_time')
   ]);
   if(!ir.error){if(ir.data?.length){const existing=new Set(ir.data.map(keyOf)),missing=seedItems.filter(x=>x.category==='Fraldas'&&!existing.has(keyOf(x)));if(missing.length)await supabase.from('items').insert(missing);setItems([...ir.data,...missing])}else{await supabase.from('items').insert(seedItems);setItems(seedItems)}}
   if(!cr.error){if(cr.data?.length)setChecklist(cr.data);else{await supabase.from('checklist').insert(seedChecklist);setChecklist(seedChecklist)}}
   if(!gr.error){if(gr.data?.length)setGifts(gr.data);else{await supabase.from('gifts').insert(seedGifts);setGifts(seedGifts)}}
   if(!er.error)setEvents(er.data||[]);
   setSync([ir.error,cr.error,gr.error,er.error].some(Boolean)?'parcial':'online');

   const channel=supabase.channel('morgana-hub-live')
    .on('postgres_changes',{event:'*',schema:'public',table:'gifts'},async()=>{const{data}=await supabase.from('gifts').select('*').order('created_at');if(data)setGifts(data)})
    .on('postgres_changes',{event:'*',schema:'public',table:'checklist'},async()=>{const{data}=await supabase.from('checklist').select('*').order('created_at');if(data)setChecklist(data)})
    .on('postgres_changes',{event:'*',schema:'public',table:'calendar_events'},async()=>{const{data}=await supabase.from('calendar_events').select('*').order('event_date').order('event_time');if(data)setEvents(data)})
    .subscribe();
   return()=>supabase.removeChannel(channel);
 })()},[]);
 useEffect(()=>{if(!hasSupabase){saveLocal(LS_ITEMS,items);saveLocal(LS_CHECK,checklist);saveLocal(LS_GIFTS,gifts);saveLocal(LS_EVENTS,events)}},[items,checklist,gifts,events]);

 async function persistItems(next){setItems(next);if(!hasSupabase)return;setSync('salvando');await supabase.from('items').delete().neq('id',0);await supabase.from('items').insert(next.map(({id,created_at,...x})=>x));setSync('online')}
 async function persistChecklist(next){setChecklist(next);if(!hasSupabase)return;setSync('salvando');await supabase.from('checklist').delete().neq('id','__never__');if(next.length)await supabase.from('checklist').insert(next.map(({created_at,...x})=>x));setSync('online')}
 async function persistGifts(next){setGifts(next);if(!hasSupabase)return;setSync('salvando');await supabase.from('gifts').delete().neq('id','__never__');if(next.length)await supabase.from('gifts').insert(next.map(({created_at,...x})=>x));setSync('online')}
 async function persistEvents(next){setEvents(next);if(!hasSupabase)return;setSync('salvando');await supabase.from('calendar_events').delete().neq('id','__never__');if(next.length)await supabase.from('calendar_events').insert(next.map(({created_at,...x})=>x));setSync('online')}

 function addToInventory(entry,qty=1){const name=entry.name,category=entry.category||'Outros';const idx=items.findIndex(x=>x.name.toLowerCase()===name.toLowerCase()&&x.category===category);let next;if(idx>=0)next=items.map((x,i)=>i===idx?{...x,quantity:Number(x.quantity||0)+Number(qty||1)}:x);else next=[...items,{name,category,quantity:Number(qty)||1,size:entry.size||'',age:entry.age||'',brand:entry.brand||'',unit:entry.unit||'unid.'}];persistItems(next)}
 function delta(i,d){persistItems(items.map((x,k)=>k===i?{...x,quantity:Math.max(0,Number(x.quantity)+d)}:x))}
 function addItem(e){e.preventDefault();const f=new FormData(e.currentTarget),x={name:f.get('name'),category:f.get('category'),quantity:Number(f.get('quantity')||1),size:f.get('size')||'',age:f.get('age')||'',brand:f.get('brand')||'',unit:f.get('unit')||'unid.'};persistItems([...items,x]);setShowItem(false)}
 async function buyChecklist(c){addToInventory(c,c.quantity);const next=checklist.filter(x=>x.id!==c.id);setChecklist(next);if(hasSupabase){await supabase.from('checklist').delete().eq('id',c.id)}else saveLocal(LS_CHECK,next)}
 async function chooseGift(e){e.preventDefault();const f=new FormData(e.currentTarget),buyer=(f.get('buyer')||'Anônimo').trim();const updated={...giftChoice,status:'purchased',buyer,purchased_at:new Date().toISOString()};const next=gifts.map(g=>g.id===updated.id?updated:g);setGifts(next);if(hasSupabase)await supabase.from('gifts').update({status:'purchased',buyer,purchased_at:updated.purchased_at}).eq('id',updated.id);setGiftChoice(null)}
 async function confirmGift(g){addToInventory(g,g.quantity);const updated={...g,status:'received',received_at:new Date().toISOString()};const next=gifts.map(x=>x.id===g.id?updated:x);setGifts(next);if(hasSupabase)await supabase.from('gifts').update({status:'received',received_at:updated.received_at}).eq('id',g.id)}
 async function releaseGift(g){const updated={...g,status:'available',buyer:'',purchased_at:null};const next=gifts.map(x=>x.id===g.id?updated:x);setGifts(next);if(hasSupabase)await supabase.from('gifts').update({status:'available',buyer:'',purchased_at:null}).eq('id',g.id)}
 function addEvent(e){e.preventDefault();const f=new FormData(e.currentTarget),ev={id:`evt-${Date.now()}`,title:f.get('title'),event_date:f.get('date'),event_time:f.get('time')||null,event_type:f.get('type')||'Tarefa',notes:f.get('notes')||'',done:false};const next=[...events,ev].sort((a,b)=>`${a.event_date}${a.event_time}`.localeCompare(`${b.event_date}${b.event_time}`));setEvents(next);if(hasSupabase)supabase.from('calendar_events').insert(ev);setShowEvent(false);setMonth(new Date(`${ev.event_date}T12:00:00`));}
 async function toggleEvent(ev){const updated={...ev,done:!ev.done};const next=events.map(x=>x.id===ev.id?updated:x);setEvents(next);if(hasSupabase)await supabase.from('calendar_events').update({done:updated.done}).eq('id',ev.id)}
 async function deleteEvent(ev){const next=events.filter(x=>x.id!==ev.id);setEvents(next);if(hasSupabase)await supabase.from('calendar_events').delete().eq('id',ev.id)}

 const totals=useMemo(()=>({fraldas:items.filter(x=>x.category==='Fraldas').reduce((a,b)=>a+Number(b.quantity||0),0),roupas:items.filter(x=>x.category==='Roupas').reduce((a,b)=>a+Number(b.quantity||0),0),lencos:items.filter(x=>x.name==='Lenços umedecidos').reduce((a,b)=>a+Number(b.quantity||0),0)}),[items]);
 const cats=['Todas',...Array.from(new Set(items.map(x=>x.category))).sort()];const filtered=items.filter(x=>(cat==='Todas'||x.category===cat)&&(`${x.name} ${x.size} ${x.age} ${x.category}`.toLowerCase().includes(q.toLowerCase())));const diapers=items.filter(x=>x.category==='Fraldas');const maxD=Math.max(...diapers.map(x=>x.quantity),1);
 const pendingGifts=gifts.filter(g=>g.status==='purchased');const availableGifts=gifts.filter(g=>g.status==='available');
 const preg=useMemo(()=>{const due=new Date(`${DUE_DATE}T12:00:00`),start=new Date(due);start.setDate(start.getDate()-280);const now=new Date();const total=due-start,elapsed=Math.max(0,Math.min(total,now-start)),pct=Math.round(elapsed/total*100),days=Math.floor(elapsed/86400000),weeks=Math.floor(days/7),rem=days%7,remaining=Math.max(0,Math.ceil((due-now)/86400000));return{pct,weeks,rem,remaining,due}},[]);
 const title=tab==='inicio'?'Olá, Morgana ♡':tab==='inventario'?'Inventário completo':tab==='recomendacoes'?'Recomendações':tab==='checklist'?'Checklist pré-nascimento':tab==='presentes'?'Presentes para a Morgana':'Calendário da família';

 return <div className="app"><aside><div className="brand"><span>✦</span><div><b>Morgana Hub</b><small>Enxoval & preparação</small></div></div>{[['inicio','⌂','Início'],['inventario','▦','Inventário'],['recomendacoes','✓','Recomendações'],['checklist','☑','Checklist'],['presentes','♡','Presente'],['calendario','◫','Calendário']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}><span>{x[1]}</span>{x[2]}</button>)}<div className="sync">● {sync==='online'?'Sincronizado online':sync==='salvando'?'Salvando…':sync==='parcial'?'Sincronização parcial':sync==='conectando'?'Conectando…':'Modo local'}<small>{hasSupabase?'Supabase conectado':'Ative o Supabase para presentes sincronizados entre celulares'}</small></div></aside><main><header><div><h1>{title}</h1><p>{tab==='inicio'?'Tudo o que vocês já têm, o que falta e os próximos compromissos.':tab==='presentes'?'Escolha um item para presentear a Morgana.':tab==='calendario'?'Consultas, exames, tarefas e compromissos em um só lugar.':'Dados baseados no inventário do chá de bebê.'}</p></div>{tab==='calendario'?<button className="primary" onClick={()=>setShowEvent(true)}>＋ Novo compromisso</button>:tab!=='presentes'&&<button className="primary" onClick={()=>setShowItem(true)}>＋ Adicionar item</button>}</header>

 {tab==='inicio'&&<><section className="hero"><div><span className="eyebrow">GESTAÇÃO</span><h2>Preparando tudo para a chegada da Morgana</h2><p>DPP: <b>17/11/2026</b> · {preg.weeks} semanas e {preg.rem} dias · {preg.remaining} dias até a data prevista.</p></div><div className="progressRing" style={{'--pct':`${preg.pct*3.6}deg`}}><b>{preg.pct}%</b><span>da gestação</span></div></section><section className="cards"><KPI n={fmt(totals.fraldas)} l="fraldas" s="estoque total"/><KPI n={fmt(totals.roupas)} l="peças de roupa" s="catalogadas"/><KPI n={fmt(totals.lencos)} l="pacotes de lenço" s="estoque alto"/><KPI n={checklist.length} l="pendências" s="checklist pré-nascimento" warn={checklist.length>0}/></section>
 <div className="grid2"><section className="panel"><div className="panelTitle"><div><small>ESTOQUE</small><h3>Fraldas por tamanho</h3></div></div><div className="bars">{diapers.map(d=><div className="barRow" key={d.name}><span>{d.size}</span><div><i style={{width:`${d.quantity/maxD*100}%`}}/></div><b>{fmt(d.quantity)}</b></div>)}</div></section><section className="panel"><div className="panelTitle"><div><small>CHECKLIST</small><h3>Próximas compras</h3></div><button onClick={()=>setTab('checklist')}>ver todas →</button></div><div className="prioList">{checklist.slice(0,5).map(r=><div className="prio" key={r.id}><span className={`dot ${r.priority==='Alta'?'red':'amber'}`}/><div><b>{r.name}</b><small>{r.category} · comprar {r.quantity}</small></div><em>{r.priority}</em></div>)}{!checklist.length&&<Empty text="Checklist concluído por enquanto."/>}</div></section></div>
 {pendingGifts.length>0&&<section className="panel giftHome"><div className="panelTitle"><div><small>PRESENTES COMPRADOS</small><h3>Aguardando chegar em nossas mãos</h3></div><button onClick={()=>setTab('presentes')}>abrir lista →</button></div><div className="giftBoughtGrid">{pendingGifts.map(g=><article className="giftBought" key={g.id}><div className="giftIcon">♡</div><div><b>{g.name}</b><small>{g.buyer?`Presente de ${g.buyer}`:'Presente reservado'} · qtd. {g.quantity}</small></div><button className="confirm" onClick={()=>confirmGift(g)}>Recebemos ✓</button></article>)}</div></section>}
 <section className="panel"><div className="panelTitle"><div><small>PRÓXIMOS DIAS</small><h3>Agenda</h3></div><button onClick={()=>setTab('calendario')}>ver calendário →</button></div><AgendaList events={events.filter(e=>!e.done&&e.event_date>=isoLocalDate(new Date())).slice(0,4)} onToggle={toggleEvent}/></section></>}

 {tab==='inventario'&&<section className="panel full"><div className="toolbar"><input placeholder="Buscar item, tamanho ou idade…" value={q} onChange={e=>setQ(e.target.value)}/><select value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div><div className="tableWrap"><table><thead><tr><th>Item</th><th>Categoria</th><th>Tamanho</th><th>Faixa</th><th>Qtd.</th></tr></thead><tbody>{filtered.map((x,i)=>{const idx=items.indexOf(x);return <tr key={`${x.name}-${i}`}><td><b>{x.name}</b><small>{x.brand}</small></td><td>{x.category}</td><td>{x.size||'—'}</td><td>{x.age||'—'}</td><td><div className="qty"><button onClick={()=>delta(idx,-1)}>−</button><b>{x.quantity}</b><button onClick={()=>delta(idx,1)}>＋</button></div></td></tr>})}</tbody></table></div></section>}

 {tab==='recomendacoes'&&<section className="recGrid">{recommendations.map(r=><article className={`recCard ${r.status.toLowerCase()}`} key={r.item}><div><span className={`badge ${String(r.priority).toLowerCase()}`}>{r.priority}</span><span className={`status ${r.status.toLowerCase()}`}>{r.status}</span></div><h3>{r.item}</h3><p>{r.note}</p><footer><span>Base <b>{r.current}</b></span><span>Meta <b>{r.min}–{r.max}</b></span></footer></article>)}</section>}

 {tab==='checklist'&&<section className="panel full"><div className="checkHeader"><div><small>ANTES DO NASCIMENTO</small><h3>Comprar / providenciar</h3></div><span>{checklist.length} pendências</span></div>{checklist.map(c=><div className="check purchase" key={c.id}><span className="checkBox">□</span><div><b>{c.name}</b><small>{c.note} · quantidade sugerida: {c.quantity}</small></div><em>{c.priority}</em><button onClick={()=>buyChecklist(c)}>Comprei ✓</button></div>)}{!checklist.length&&<Empty text="Tudo desta lista já foi providenciado. Os itens comprados foram adicionados ao inventário."/>}</section>}

 {tab==='presentes'&&<><section className="giftIntro"><div><span className="eyebrow">LISTA DE PRESENTES</span><h2>Quer presentear a Morgana?</h2><p>Escolha um item disponível. Assim que você marcar como comprado, ele fica reservado e aparece para a família como “aguardando chegar”.</p></div><span className="giftCount">{availableGifts.length}<small>disponíveis</small></span></section>{!hasSupabase&&<div className="notice">⚠️ Este Hub está em modo local. Para que convidados em outros celulares atualizem esta lista, conecte o Supabase na Vercel.</div>}<section className="giftGrid">{gifts.filter(g=>g.status!=='received').map(g=><article className={`giftCard ${g.status}`} key={g.id}><div className="giftTop"><span>{g.category}</span><b>{g.status==='available'?'Disponível':'Comprado'}</b></div><h3>{g.name}</h3><p>{g.note}</p><footer><span>Qtd. {g.quantity}</span>{g.status==='available'?<button className="primary" onClick={()=>setGiftChoice(g)}>Vou presentear ♡</button>:<div className="giftReserved"><span>{g.buyer?`por ${g.buyer}`:'reservado'}</span><button onClick={()=>releaseGift(g)}>liberar</button></div>}</footer></article>)}</section></>}

 {tab==='calendario'&&<Calendar month={month} setMonth={setMonth} events={events} onToggle={toggleEvent} onDelete={deleteEvent} onAdd={()=>setShowEvent(true)}/>} 
 </main>
 {showItem&&<div className="modalBack" onMouseDown={()=>setShowItem(false)}><form className="modal" onSubmit={addItem} onMouseDown={e=>e.stopPropagation()}><div><h2>Adicionar item</h2><button type="button" onClick={()=>setShowItem(false)}>×</button></div><label>Nome<input required name="name"/></label><div className="two"><label>Categoria<select name="category">{cats.filter(x=>x!=='Todas').map(c=><option key={c}>{c}</option>)}<option>Outros</option></select></label><label>Quantidade<input name="quantity" type="number" min="0" defaultValue="1"/></label></div><div className="two"><label>Tamanho<input name="size"/></label><label>Idade / faixa<input name="age"/></label></div><div className="two"><label>Marca<input name="brand"/></label><label>Unidade<input name="unit" defaultValue="unid."/></label></div><button className="primary wide">Salvar item</button></form></div>}
 {giftChoice&&<div className="modalBack" onMouseDown={()=>setGiftChoice(null)}><form className="modal giftModal" onSubmit={chooseGift} onMouseDown={e=>e.stopPropagation()}><div><h2>Presentear a Morgana ♡</h2><button type="button" onClick={()=>setGiftChoice(null)}>×</button></div><div className="selectedGift"><small>VOCÊ ESCOLHEU</small><b>{giftChoice.name}</b><span>Quantidade: {giftChoice.quantity}</span></div><label>Seu nome <small>(opcional)</small><input name="buyer" placeholder="Como a família vai identificar o presente"/></label><p className="fine">Ao confirmar, este item ficará marcado como comprado para evitar presentes duplicados.</p><button className="primary wide">Confirmar presente</button></form></div>}
 {showEvent&&<div className="modalBack" onMouseDown={()=>setShowEvent(false)}><form className="modal" onSubmit={addEvent} onMouseDown={e=>e.stopPropagation()}><div><h2>Novo compromisso</h2><button type="button" onClick={()=>setShowEvent(false)}>×</button></div><label>Título<input required name="title" placeholder="Ex.: Ultrassom, consulta, comprar item…"/></label><div className="two"><label>Data<input required type="date" name="date" defaultValue={isoLocalDate(new Date())}/></label><label>Horário<input type="time" name="time"/></label></div><label>Categoria<select name="type"><option>Consulta</option><option>Exame</option><option>Tarefa</option><option>Trabalho</option><option>Outro</option></select></label><label>Observação<textarea name="notes" rows="3" placeholder="Endereço, médico, lembrete para o trabalho…"/></label><button className="primary wide">Adicionar ao calendário</button></form></div>}
 </div>
}

function Calendar({month,setMonth,events,onToggle,onDelete,onAdd}){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),offset=first.getDay(),cells=[];for(let i=0;i<offset;i++)cells.push(null);for(let d=1;d<=last.getDate();d++)cells.push(new Date(y,m,d));while(cells.length%7)cells.push(null);const monthEvents=events.filter(e=>{const d=new Date(`${e.event_date}T12:00:00`);return d.getFullYear()===y&&d.getMonth()===m});const label=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(month);return <div className="calendarLayout"><section className="panel calendarPanel"><div className="calendarNav"><button onClick={()=>setMonth(new Date(y,m-1,1))}>‹</button><h2>{label}</h2><button onClick={()=>setMonth(new Date(y,m+1,1))}>›</button></div><div className="weekHead">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(x=><b key={x}>{x}</b>)}</div><div className="monthGrid">{cells.map((d,i)=>{if(!d)return <div className="day empty" key={`e${i}`}/>;const iso=isoLocalDate(d),dayEvents=events.filter(e=>e.event_date===iso),today=iso===isoLocalDate(new Date());return <div className={`day ${today?'today':''}`} key={iso}><span>{d.getDate()}</span>{dayEvents.slice(0,3).map(e=><i className={`evtDot ${e.done?'done':''}`} title={e.title} key={e.id}>{e.event_time||'•'} {e.title}</i>)}{dayEvents.length>3&&<small>+{dayEvents.length-3}</small>}</div>})}</div></section><section className="panel agendaSide"><div className="panelTitle"><div><small>AGENDA DO MÊS</small><h3>{monthEvents.length} compromissos</h3></div><button onClick={onAdd}>＋ adicionar</button></div>{monthEvents.sort((a,b)=>`${a.event_date}${a.event_time}`.localeCompare(`${b.event_date}${b.event_time}`)).map(e=><div className={`agendaItem ${e.done?'done':''}`} key={e.id}><button className="agendaCheck" onClick={()=>onToggle(e)}>{e.done?'✓':'○'}</button><div><b>{e.title}</b><small>{dateOnly(new Date(`${e.event_date}T12:00:00`))}{e.event_time?` às ${e.event_time}`:''} · {e.event_type}</small>{e.notes&&<p>{e.notes}</p>}</div><button className="trash" onClick={()=>onDelete(e)}>×</button></div>)}{!monthEvents.length&&<Empty text="Nenhum compromisso neste mês."/>}</section></div>}
function AgendaList({events,onToggle}){return <div>{events.map(e=><div className="agendaItem compact" key={e.id}><button className="agendaCheck" onClick={()=>onToggle(e)}>○</button><div><b>{e.title}</b><small>{dateOnly(new Date(`${e.event_date}T12:00:00`))}{e.event_time?` às ${e.event_time}`:''} · {e.event_type}</small></div></div>)}{!events.length&&<Empty text="Nenhum compromisso futuro cadastrado."/>}</div>}
function Empty({text}){return <div className="emptyState">✦ <span>{text}</span></div>}
function KPI({n,l,s,warn}){return <article className={`kpi ${warn?'warn':''}`}><small>{s}</small><strong>{n}</strong><b>{l}</b></article>}
createRoot(document.getElementById('root')).render(<App/>);
